Fixing Segfault in privsep-root 10.0.1
NetworkConfiguration/dhcpcd pull request #219
Opened 2023-07-01 17:53 UTC by archcloudlabs

OS: Arch Linux
Version: dhcpcd 10.0.1

Currently, with dhcpcd 10.0.1 when executing the binary as a non-root user, a segfault occurs when dereferencing values from a struct that is not populated.
![error](https://github.com/NetworkConfiguration/dhcpcd/assets/1250113/e9ffb43a-8b09-436e-8955-adfe74e4f8c1)

This PR addresses this issue by checking whether or not the the uid is 0.
![fix](https://github.com/NetworkConfiguration/dhcpcd/assets/1250113/6b11cd2c-c5ca-4d9e-b169-349e0c9911bb)

2023-07-01 19:29 UTC, igalic requested changes

2023-07-01 19:29 UTC, igalic commented on src/privsep-root.c
> +	if (getuid() == 0 ) {
maybe preserve the indentation level by combining these two conditions with an `&&`.

Also extend the comment above explaining why the `getuid()` check is necessary

2023-07-02 00:31 UTC, closed without merging

2023-07-02 00:32 UTC, rsmarples commented
Thanks for the report, the fix you provided can be done a lot better.
Your diagnosis was spot on, but we only need to unlink if the struct is populated in the first place so just testing if the first element is not null is sufficient.

2023-07-02 01:50 UTC, archcloudlabs commented
Thanks for the feedback!