add RFC4191 support
NetworkConfiguration/dhcpcd pull request #297
Opened 2024-02-21 19:35 UTC by goertzenator

Resolves issue #102.

Implement RFC4191 support for Route Information options in Router Advertisements.  This option allows a router to provide routes for a specific prefix instead of only providing default routes.

My use case is that I have a ULA network with a VPN router and no IPv6 internet access.  Using this router as the default route does not work well because the host then thinks it can reach the Internet.  By instead advertising a route just for the ULA prefix hosts will immediately know they cannot reach the Internet through this router.

I've tested this PR in a VM in this exact configuration and it seems to work quite well.  I changed the radvd config on the fly to remove and add the route and it behaved as expected.

2024-02-22 12:16 UTC, rsmarples requested changes
Technically it looks sound.
I've made some comments mainly on style but some recommendations also.

Thanks for the effort thus far!

2024-02-22 12:16 UTC, rsmarples commented on src/ipv6nd.c
> +	clock_gettime(CLOCK_MONOTONIC, &ri->acquired);
We could use the  acquired time of the RA here instead of a call to get the monotonic clock.

2024-02-22 12:16 UTC, rsmarples commented on src/sa.c
> +ipbytes_fromprefix(uint8_t *ap, int prefix, int max_prefix)
Why did you change this? It's not used outside of sa in this branch AFAIK.

2024-02-22 12:16 UTC, rsmarples commented on src/ipv6nd.h
> +int ipv6nd_rtpref(uint8_t);
Why did you change this?

2024-02-22 12:16 UTC, rsmarples commented on src/ipv6nd.c
> +	ri = calloc(1, sizeof(struct routeinfo));
malloc should be sufficient here.
Yes there will be undefined bytes inside the prefix as length will likely be less, but that's fine as we always access limited via prefixlength.

2024-02-22 12:16 UTC, rsmarples commented on src/ipv6nd.h
> +	uint8_t prefixlength;
please rename to prefix_len and move to underneath the prefix to match ipv6.h
Move acquired to just above sprefix.

2024-02-22 12:16 UTC, rsmarples commented on src/ipv6nd.h
> +	struct routeinfohead routeinfos;
Please rename to rinfos.
To save many comments, please rename all local routeinfo variables to rinfo.

2024-02-22 15:00 UTC, goertzenator commented on src/ipv6nd.h
> +	struct routeinfohead routeinfos;
Would you like `struct routeinfo` to `struct rinfo` too? (same for `routeinfohead` -> `rinfohead`)

2024-02-22 15:03 UTC, rsmarples commented on src/ipv6nd.h
> +	struct routeinfohead routeinfos;
No routeinfo is fine for the struct name.

2024-02-22 15:34 UTC, goertzenator commented on src/sa.c
> +ipbytes_fromprefix(uint8_t *ap, int prefix, int max_prefix)
We compute a netmask from a prefix_len [here](https://github.com/goertzenator/dhcpcd/blob/rfc4191route/src/ipv6.c#L2339).  The original fromprefix function only operated on a `struct sockaddr` which `rinfo` does not have or need.  I unwrapped the prefix code in sa.c to make it usable for `rinfo`.

`ipbytes_fromprefix()` should be static and removed from sa.h since it is indeed only used inside sa.c.

2024-02-23 02:02 UTC, rsmarples commented on src/ipv6nd.c
> +				rap->lifetime = ntohl(ri.nd_opt_ri_lifetime);
The warning here:
https://github.com/goertzenator/dhcpcd/blob/rfc4191route/src/ipv6nd.c#L1258

Needs to be moved to here:
https://github.com/goertzenator/dhcpcd/blob/rfc4191route/src/ipv6nd.c#L1602

2024-02-23 14:26 UTC, goertzenator commented on src/ipv6nd.c
> +				rap->lifetime = ntohl(ri.nd_opt_ri_lifetime);
Ah, I understand now.  Good catch!

2024-02-23 14:27 UTC, goertzenator commented
Thanks for the prompt review, I appreciate it!

2024-03-04 23:50 UTC, rsmarples commented on src/ipv6nd.c
> +			rinfo = routeinfo_find(rap, &ri.nd_opt_ri_prefix, ri.nd_opt_ri_prefixlen);
I would make this simpler.

Rename routeinfo_find to routeinfo_alloc (or findalloc) and pass the same arguments as here.
Then below if NULL, break (ensure error reported somewhere) if not then assign the rest of the data.
This avoids two different places to assign the same data.

2024-03-08 21:26 UTC, goertzenator commented on src/ipv6nd.c
> +			rinfo = routeinfo_find(rap, &ri.nd_opt_ri_prefix, ri.nd_opt_ri_prefixlen);
Changes made as requested.

2024-03-09 01:27 UTC, merged

2024-03-09 01:28 UTC, rsmarples commented
Thanks for your contribution!