dhcpcd: Respect IPV6_PREFERRED_ONLY flag regardless of state
NetworkConfiguration/dhcpcd pull request #307
Opened 2024-03-12 02:44 UTC by taoyl-g

Current IPv6_PREFERRED_ONLY (option 108) handling code is only effective when current state is DHS_DISCOVER or DHS_REBOOT. However the assumption that we'll only receive OFFER and ACK with option 108 in those two states is not true. Particularly, when we receive multiple ACKs upon our REQUEST, the first ACK will trigger the use_v6only code path and dhcp_drop() us into DHS_NONE state, therefore the option 108 on second ACK won't be handled correctly and we'll bind to the lease incorrectly.

DHS_NONE is not the only possible state, considering the corner cases of server configuration change and multiple servers. Thus we shoulf just remove the state check here.

2024-03-28 17:05 UTC, rsmarples commented
https://datatracker.ietf.org/doc/html/rfc8925#section-3.2

```
If the client is in any other state, it SHOULD continue to use the assigned IPv4 address until further DHCPv4 reconfiguration events.
```

So we need to add the NONE state to the list, not just remove the list.

2024-03-28 17:06 UTC, rsmarples requested changes
https://datatracker.ietf.org/doc/html/rfc8925#section-3.2

```
If the client is in any other state, it SHOULD continue to use the assigned IPv4 address until further DHCPv4 reconfiguration events.
```

So we need to add the NONE state to the list, not just remove the list.

2024-04-02 07:07 UTC, taoyl-g commented
Thanks for the RFC pointer. I've updated the patch.

2024-04-02 08:29 UTC, rsmarples approved these changes

2024-04-02 09:07 UTC, merged

2024-04-02 09:08 UTC, rsmarples commented
Thanks!