DHCPv6: Add support for sending Option 17 (VSIO)
NetworkConfiguration/dhcpcd pull request #374
Opened 2024-10-04 12:17 UTC by spoljak-ent

Hi,
I made a patch for the support of sending DHCPv6 Option 17.
The options can be added similarly to the current vendor option 43.

Just add in config file as many options as needed like this:
vsio ent_num opt_num,option

Please comment and review.
Thanks.

2024-10-08 15:22 UTC, rsmarples requested changes
Can we wrap this in `#ifndef SMALL` please so we don't bloat the code for installations where size matters?

2024-10-08 15:22 UTC, rsmarples commented on src/dhcp6.c
> +		i++, vsio6++) {
Rather than increment two things, we can just increment vsio6.
For this to work we need to work out the address of the final pointer using vsio6_len.
`*vsio6_endp = ifo->vsio6 + ifo->vsio6_len` and then compare.
I would front load this in the variable declaration at the top to reduce the number of  lines the for loop takes up.

2024-10-08 15:22 UTC, rsmarples commented on src/dhcp6.c
> +		}
This should be one indent to the left.

2024-10-08 15:22 UTC, rsmarples commented on src/dhcp6.c
> +			i++, vsio6++) {
Same as above.

2024-10-09 12:24 UTC, spoljak-ent commented
> Can we wrap this in `#ifndef SMALL` please so we don't bloat the code for installations where size matters?

No problem... Just to be sure, the whole implementation or something specific?

2024-10-10 10:25 UTC, closed without merging

2024-10-10 10:44 UTC, rsmarples commented
> > Can we wrap this in `#ifndef SMALL` please so we don't bloat the code for installations where size matters?
> 
> No problem... Just to be sure, the whole implementation or some specific lines?

Whole implementation please.

2024-10-10 11:04 UTC, spoljak-ent commented
> > > Can we wrap this in `#ifndef SMALL` please so we don't bloat the code for installations where size matters?
> > 
> > 
> > No problem... Just to be sure, the whole implementation or some specific lines?
> 
> Whole implementation please.
Sure thing.
Had to pull recent changes and everything was overwritten... I've created a new pull request for this:
https://github.com/NetworkConfiguration/dhcpcd/pull/382