Apply lastlease behavior to DHCPv6
NetworkConfiguration/dhcpcd pull request #381
Opened 2024-10-09 20:58 UTC by jvfranklin

If no response is received to Confirm messages, instead of failing, go ahead and use the lease, as recommended by RFC 8415 18.2.3. Enabled by the "lastlease" config option.

2024-10-10 14:04 UTC, rsmarples requested changes

2024-10-10 14:04 UTC, rsmarples commented on src/dhcp6.c
> +		dhcp6_bind(ifp, "REPLY6", NULL);
op should be NULL, not REPLY6. With a NULL op we get the TIMEOUT6 as the hook reason.
We might want to add TIMEOUT6 to the dhcpcd-run-hooks,8 man page as well - it's missing!

2024-10-10 14:04 UTC, rsmarples commented on src/dhcpcd.conf.5.in
> +.It Ic lastlease
Please bump the date at the top of this file as well.

2024-10-10 16:14 UTC, rsmarples commented on src/dhcp6.c
> +	if (ifp->options->options & DHCPCD_LASTLEASE)
I feel that this should be moved into `dhcp6_fail()` where the logic goes

```
if (drop) {
...
} else if (state->recv && ifp->options->options & DHCPCD_LASTLEASE) {
   dhcp6_bind()
} else if (state->new) {
 ...
}
```

That way, Prefix Delegation renew failure would be supported this way as well and that part of the RFC is also should so might be part of the tests.

What do you think? Also, can you test it? :)

2024-10-10 16:34 UTC, jvfranklin commented on src/dhcp6.c
> +	if (ifp->options->options & DHCPCD_LASTLEASE)
Sure, I can make that change. I'm able to run the IPv6 Ready Logo tests, but my environment is kind of limited. I can only do the client tests, but not PD stuff.  And it takes up to 48 hours to run depending on the tests I pick, so it'll be a bit before I can get back to you.

2024-10-10 16:59 UTC, rsmarples commented on src/dhcp6.c
> +	if (ifp->options->options & DHCPCD_LASTLEASE)
That's fine. The lease code flow is exactly the same of what we want to do, so if your path works then the PD path will work just as well.

If either fail, we want to re-start the discovery process again as a server might not be authoritative and silently ignore us so we use our prior lease and then try and get a new one. This is the mirror of DHCP behavior so I think it will work well.

2024-10-11 14:00 UTC, jvfranklin commented
The changes don't seem to be causing any issues with the Ready Logo tests I ran. I didn't run the really long ones, but those check retransmission times, etc, and not failures, so I figured they wouldn't really be relevant.

2024-10-11 17:10 UTC, rsmarples commented on src/dhcp6.c
> +	if (ifp->options->options & DHCPCD_LASTLEASE)
Looks good, but we now need to revert this section of code now the logic is in dhcp6_fail()

2024-10-11 18:16 UTC, jvfranklin commented on src/dhcp6.c
> +	if (ifp->options->options & DHCPCD_LASTLEASE)
Sorry, I'm not sure what happened. The commit in my local branch has that already, not sure why it didn't show up in the PR. Let me just cancel this PR, clean it up and submit a new one. Sorry for the mess...

2024-10-11 18:42 UTC, closed without merging