Fix using multiple enterprise IDs with vendclass (Option 124 DHCP / Option 16 DHCPv6) (#328)
NetworkConfiguration/dhcpcd pull request #408
Opened 2024-11-21 08:24 UTC by spoljak-ent

As it's outlined in #328, using multiple enterprise IDs with vendclass overwrites all previous values.
This fixes the issue.

2024-11-21 11:59 UTC, rsmarples requested changes

2024-11-21 11:59 UTC, rsmarples commented on src/if-options.c
> +				return -1;
Maybe a better text would be "vendor class option for enterprise number %u already defined".
We might also want to consider do we want to have a different option sent for the same enterprise number based on interface or profile name? If so, we might just want to silently override it instead.

Thoughts?

2024-11-21 11:59 UTC, rsmarples commented on src/dhcp.c
> +			for (vivco = ifo->vivco; vivco != vivco_endp; vivco++)
White space between the declaration and the code please, but see below comment first.

2024-11-21 11:59 UTC, rsmarples commented on src/dhcp.c
>  				memcpy(p, vivco->data, vivco->len);
This could be re-written as
```
*p++ = (uint8_t)(sizeof(uint8_t) + vivco->len);
*p++ = (uint8_t)(vivco->len);
```

Much smaller code and no need to declare the variables then.

2024-11-21 12:00 UTC, rsmarples commented
RFC 3925 says
> Multiple instances of this option may be present
   and MUST be concatenated in accordance with [RFC 3396](https://datatracker.ietf.org/doc/html/rfc3396) [[4](https://datatracker.ietf.org/doc/html/rfc3925#ref-4)].

So we should try and use the rfc3396 encoding functions we added in the previous PR to help here.

2024-11-21 12:35 UTC, spoljak-ent commented on src/if-options.c
> +				return -1;
Yeah, it is better regarding the text.
Regarding the different option, I was going along with RFC 3925 that we should have only one enterprise number among all instances of this option.
How would this work with the silent override?

2024-11-21 12:36 UTC, spoljak-ent commented on src/dhcp.c
>  				memcpy(p, vivco->data, vivco->len);
Agreed, I'll fix it.

2024-11-21 12:38 UTC, spoljak-ent commented
> RFC 3925 says
> 
> > Multiple instances of this option may be present
> > and MUST be concatenated in accordance with [RFC 3396](https://datatracker.ietf.org/doc/html/rfc3396) [[4](https://datatracker.ietf.org/doc/html/rfc3925#ref-4)].
> 
> So we should try and use the rfc3396 encoding functions we added in the previous PR to help here.

We could, but I wasn't sure about adding (much) more code since the previous PR was wrapped in #ifndef SMALL.

2024-11-21 12:40 UTC, rsmarples commented
> > RFC 3925 says
> > > Multiple instances of this option may be present
> > > and MUST be concatenated in accordance with [RFC 3396](https://datatracker.ietf.org/doc/html/rfc3396) [[4](https://datatracker.ietf.org/doc/html/rfc3925#ref-4)].
> > 
> > 
> > So we should try and use the rfc3396 encoding functions we added in the previous PR to help here.
> 
> We could, but I wasn't sure about adding (much) more code since the previous PR was wrapped in #ifndef SMALL.

We should wrap this code in `#ifndef SMALL` as well really.

2024-11-21 12:46 UTC, spoljak-ent commented
> > > RFC 3925 says
> > > > Multiple instances of this option may be present
> > > > and MUST be concatenated in accordance with [RFC 3396](https://datatracker.ietf.org/doc/html/rfc3396) [[4](https://datatracker.ietf.org/doc/html/rfc3925#ref-4)].
> > > 
> > > 
> > > So we should try and use the rfc3396 encoding functions we added in the previous PR to help here.
> > 
> > 
> > We could, but I wasn't sure about adding (much) more code since the previous PR was wrapped in #ifndef SMALL.
> 
> We should wrap this code in `#ifndef SMALL` as well really.

Got it. I'll make the changes.

2024-11-21 13:25 UTC, spoljak-ent commented on src/if-options.c
> +				return -1;
Sorry for the confusion, I meant about having a different option sent for the same enterprise number based on interface or profile name. Haven't worked with multiple profiles/interfaces tbh.

2024-11-22 07:46 UTC, spoljak-ent commented on src/dhcp.c
>  				memcpy(p, vivco->data, vivco->len);
Made the requested change with RFC3396 ctx. 
Looks much cleaner now.

2024-11-22 08:13 UTC, spoljak-ent commented on src/dhcp.c
> +			for (vivco = ifo->vivco; vivco != vivco_endp; vivco++)
Resolved with RFC3396 ctx.

2024-11-22 08:14 UTC, spoljak-ent commented
> > > > RFC 3925 says
> > > > > Multiple instances of this option may be present
> > > > > and MUST be concatenated in accordance with [RFC 3396](https://datatracker.ietf.org/doc/html/rfc3396) [[4](https://datatracker.ietf.org/doc/html/rfc3925#ref-4)].
> > > > 
> > > > 
> > > > So we should try and use the rfc3396 encoding functions we added in the previous PR to help here.
> > > 
> > > 
> > > We could, but I wasn't sure about adding (much) more code since the previous PR was wrapped in #ifndef SMALL.
> > 
> > 
> > We should wrap this code in `#ifndef SMALL` as well really.
> 
> Got it. I'll make the changes.

All required changes done... for now 😄

2024-11-22 09:22 UTC, rsmarples reviewed
This is looking good now, thanks.

I'm currently in the process of moving house so won't get a chance to actually test it for Some Time.

2024-11-22 09:22 UTC, rsmarples commented on src/dhcp.c
> +					(uint8_t)vivco->len) == -1)
Where the line breaks or flows onto the next, please use 4 spaces rather than a tab.
I should really force an opinionated formatter on pull requests at some point :)

2024-11-22 09:36 UTC, spoljak-ent commented on src/dhcp.c
> +					(uint8_t)vivco->len) == -1)
Noted and corrected :)

2025-01-18 09:39 UTC, perkelix commented
@rsmarples ready to merge?

2025-01-18 11:46 UTC, merged